namespace helengine.psvita.builder.tests;

/// <summary>
/// Provides deterministic successful device outputs for host-side Vita shader bundle compiler tests.
/// </summary>
public sealed class PsVitaShaderBundleCompilerTestExchange : IPsVitaShaderCompilerExchange {
    /// <summary>
    /// Stores artifacts by the result path generated for each submitted stage.
    /// </summary>
    readonly Dictionary<string, byte[]> ArtifactBytesByPath;

    /// <summary>
    /// Stores the successful result generated from the submitted job.
    /// </summary>
    PsVitaShaderCompilerResult Result;

    /// <summary>
    /// Initializes the deterministic exchange fixture.
    /// </summary>
    public PsVitaShaderBundleCompilerTestExchange() {
        ArtifactBytesByPath = new Dictionary<string, byte[]>(StringComparer.Ordinal);
    }

    /// <summary>
    /// Gets the complete batch job submitted by the compiler under test.
    /// </summary>
    public PsVitaShaderCompilerJob SubmittedJob { get; private set; }

    /// <summary>
    /// Gets the source files submitted beside the complete batch job.
    /// </summary>
    public IReadOnlyList<PsVitaShaderCompilerSourceFile> SubmittedSourceFiles { get; private set; }

    /// <summary>
    /// Records the batch job and synthesizes matching serialized stage artifacts.
    /// </summary>
    /// <param name="job">Submitted compiler job.</param>
    /// <param name="sourceFiles">Submitted stage-specific source files.</param>
    public void Submit(PsVitaShaderCompilerJob job, IReadOnlyList<PsVitaShaderCompilerSourceFile> sourceFiles) {
        SubmittedJob = job ?? throw new ArgumentNullException(nameof(job));
        if (sourceFiles == null || sourceFiles.Count != job.Stages.Count) {
            throw new ArgumentException("Every submitted stage requires one source file.", nameof(sourceFiles));
        }

        SubmittedSourceFiles = sourceFiles.ToArray();
        ArtifactBytesByPath.Clear();
        PsVitaShaderCompilerStageResult[] stages = new PsVitaShaderCompilerStageResult[job.Stages.Count];
        for (int index = 0; index < job.Stages.Count; index++) {
            PsVitaShaderCompilerStageRequest stage = job.Stages[index];
            string artifactPath = string.Concat(stage.StageId, ".pvsa");
            byte[] artifactBytes = CreateArtifact(stage.Profile, stage.EntryPoint, stage.OptionsSignature, [(byte)(index + 1)]);
            PsVitaShaderArtifact artifact = new PsVitaShaderArtifactBinarySerializer().Deserialize(artifactBytes);
            ArtifactBytesByPath.Add(artifactPath, artifactBytes);
            stages[index] = new PsVitaShaderCompilerStageResult(stage.StageId, true, string.Empty, artifactPath, artifact.ArtifactHash, artifact.ProgramBytes.Length);
        }

        Result = new PsVitaShaderCompilerResult(job.JobHash, stages);
    }

    /// <summary>
    /// Returns the generated result for the submitted job identity.
    /// </summary>
    /// <param name="jobHash">Device job identity requested by the compiler.</param>
    /// <param name="result">Matching generated result manifest.</param>
    /// <returns>True after a job has been submitted with the requested identity.</returns>
    public bool TryReadResult(string jobHash, out PsVitaShaderCompilerResult result) {
        if (SubmittedJob != null && string.Equals(SubmittedJob.JobHash, jobHash, StringComparison.Ordinal)) {
            result = Result;
            return true;
        }

        result = null;
        return false;
    }

    /// <summary>
    /// Returns the generated serialized artifact at the result-reported relative path.
    /// </summary>
    /// <param name="jobHash">Device job identity requested by the compiler.</param>
    /// <param name="artifactPath">Result-reported artifact path.</param>
    /// <param name="artifactBytes">Complete serialized artifact bytes when available.</param>
    /// <returns>True when the requested job and artifact path were generated by the fixture.</returns>
    public bool TryReadArtifact(string jobHash, string artifactPath, out byte[] artifactBytes) {
        if (SubmittedJob != null && string.Equals(SubmittedJob.JobHash, jobHash, StringComparison.Ordinal) && ArtifactBytesByPath.TryGetValue(artifactPath, out byte[] storedBytes)) {
            artifactBytes = storedBytes.ToArray();
            return true;
        }

        artifactBytes = Array.Empty<byte>();
        return false;
    }

    /// <summary>
    /// Creates one serialized artifact matching a submitted compiler stage request.
    /// </summary>
    /// <param name="profile">Expected Vita stage profile.</param>
    /// <param name="entryPoint">Expected stage entry-point name.</param>
    /// <param name="optionsSignature">Expected deterministic compiler option signature.</param>
    /// <param name="programBytes">Compiled program payload fixture.</param>
    /// <returns>Serialized PVSA artifact bytes.</returns>
    static byte[] CreateArtifact(string profile, string entryPoint, string optionsSignature, byte[] programBytes) {
        PsVitaShaderArtifact artifact = new(
            profile,
            "libshacccg-test",
            Convert.ToHexString(System.Security.Cryptography.SHA256.HashData("source"u8)),
            entryPoint,
            optionsSignature,
            programBytes);
        return new PsVitaShaderArtifactBinarySerializer().Serialize(artifact);
    }
}
